// 路由列表
const urlList = {
  'homeSwiperImgList': 'home/homeSwiperImgList',
  'homeNewsList': 'home/homeNewsList',
  'hotGoods': 'home/hotGoods',
  'goodsList': 'market/goodsList',
  'leftList': 'rentLand/leftList',
  'login': 'login',
  'register': 'register',
  "changePass": "user/changePass",
  "address": "user/address",
  "newAddress": "user/newAddress",
  "changeIntegral": "user/changeIntegral",
  "getUserSignDays": "user/getUserSignDays",
  "getUserInfo": "user/getUserInfo",
  "getAlls": "coupon/getAlls",
  "myCoupon": "coupon/myCoupon",
  "handleCoupon": "coupon/handleCoupon",
  "new": "coupon/new",
  "getAllGoods": "goods/getAlls",
  "getCarts": "order/getCarts",
  "handleCart": "order/handleCart",
};
