// 路由列表
const urlList = {
  // 首页接口
  'homeSwiperImgList': '/home/homeSwiperImgList',
  // 登录注册接口
  'login': '/user/login',
  'register': '/user/register',
  // 用户接口
  "changePass": "/user/changePass",
  "address": "/user/address",
  "defaultAddress": "/user/defaultAddress",
  "newAddress": "/user/newAddress",
  "changeIntegral": "/user/changeIntegral",
  "getUserSignDays": "/user/getUserSignDays",
  "myFarms": "/user/farmOrder",
  "getUserInfo": "/user/getUserInfo",
  "userIfExit": "/user/ifExit",
  "updateImg": "/user/updateCover",
  // 优惠卷接口
  "getAlls": "/coupon/getAlls",
  "myCoupon": "/coupon/myCoupon",
  "handleCoupon": "/coupon/handleCoupon",
  "new": "/coupon/new",
  // 商品接口
  "getAllGoods": "/goods/getAlls",
  "updateGood": "/goods/update",
  "updateGoodStatus": "/goods/updateStatus",
  "getGoodInfo": "/goods/getInfo",
  "saveId": "/goods/saveId",
  "getId": "/goods/getId",
  "newGood": "/goods/new",
  // 订单接口
  "newOrder": "/order/new",
  "allOrders": "/order/all",
  "modifyOrderStatus": "/order/modify",
  "SunpayOrders": "/order/unpay",
  // 购物车接口
  "deleteCart": "/cart/delete",
  "handleCart": "/cart/handle",
  "getCarts": "/cart/getAlls",
  "updateCarts": "/cart/update",
  // 商家接口
  "SgetAllSuppliers": "/supplier/getAll",
  "SgetSupplierById": "/supplier/getSupplierById",
  "Ssregister": "/supplier/register",
  "Sslogin": "/supplier/login",
  "SsupplierFarm": "/supplier/farms",
  "SsupplierGood": "/supplier/goods",
  "SsupplierOrders": "/supplier/orders",
  "SsupplierIfExit": "/supplier/ifExit",
  "SsupplierMessage": "/supplier/message",
  // 农场接口
  "getFarmsInfo": "/farm/getInfo",
  "getAllFarmsInfo": "/farm/getAlls",
  "newFarmOrder": "/farm/newOrder",
  "newFarm": "/farm/newFarm",
  "newCrop": "/farm/newCrop",
  // 通信接口
  "sMessage": "/socket/sMessage",
  "servicerHistory": "/socket/servicerHistory",
  "supplierHistory": "/socket/supplierHistory",
  // 通用接口
  "upload": "/utils/upload",
  "startTask": "/utils/startTask",
};
